-- Insert Idea Categories
INSERT INTO idea_categories (idea_id, category_id) SELECT 1,c.id FROM categories c WHERE c.name ilike 'Books';
INSERT INTO idea_categories (idea_id, category_id) SELECT 2,c.id FROM categories c WHERE c.name ilike 'Jewelry';
INSERT INTO idea_categories (idea_id, category_id) SELECT 3,c.id FROM categories c WHERE c.name ilike 'Watches';
INSERT INTO idea_categories (idea_id, category_id) SELECT 4,c.id FROM categories c WHERE c.name ilike 'Candles';
INSERT INTO idea_categories (idea_id, category_id) SELECT 5,c.id FROM categories c WHERE c.name ilike 'Chocolate';
INSERT INTO idea_categories (idea_id, category_id) SELECT 5,c.id FROM categories c WHERE c.name ilike 'Desserts';
INSERT INTO idea_categories (idea_id, category_id) SELECT 6,c.id FROM categories c WHERE c.name ilike 'Wine';
INSERT INTO idea_categories (idea_id, category_id) SELECT 6,c.id FROM categories c WHERE c.name ilike 'Food Tourism';
INSERT INTO idea_categories (idea_id, category_id) SELECT 6,c.id FROM categories c WHERE c.name ilike 'Solo Travel';
INSERT INTO idea_categories (idea_id, category_id) SELECT 7,c.id FROM categories c WHERE c.name ilike 'Wireless Earbuds';
INSERT INTO idea_categories (idea_id, category_id) SELECT 7,c.id FROM categories c WHERE c.name ilike 'Music';
INSERT INTO idea_categories (idea_id, category_id) SELECT 8,c.id FROM categories c WHERE c.name ilike 'Books';
INSERT INTO idea_categories (idea_id, category_id) SELECT 8,c.id FROM categories c WHERE c.name ilike 'E-Readers';
INSERT INTO idea_categories (idea_id, category_id) SELECT 9,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 9,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 10,c.id FROM categories c WHERE c.name ilike 'Smartwatches';
INSERT INTO idea_categories (idea_id, category_id) SELECT 11,c.id FROM categories c WHERE c.name ilike 'Coffee';
INSERT INTO idea_categories (idea_id, category_id) SELECT 11,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 12,c.id FROM categories c WHERE c.name ilike 'Photography';
INSERT INTO idea_categories (idea_id, category_id) SELECT 13,c.id FROM categories c WHERE c.name ilike 'Smart Home Gadgets';
INSERT INTO idea_categories (idea_id, category_id) SELECT 13,c.id FROM categories c WHERE c.name ilike 'Music';
INSERT INTO idea_categories (idea_id, category_id) SELECT 14,c.id FROM categories c WHERE c.name ilike 'Wireless Earbuds';
INSERT INTO idea_categories (idea_id, category_id) SELECT 14,c.id FROM categories c WHERE c.name ilike 'Music';
INSERT INTO idea_categories (idea_id, category_id) SELECT 15,c.id FROM categories c WHERE c.name ilike 'Tablets';
INSERT INTO idea_categories (idea_id, category_id) SELECT 16,c.id FROM categories c WHERE c.name ilike 'Tablets';
INSERT INTO idea_categories (idea_id, category_id) SELECT 17,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 18,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 18,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 19,c.id FROM categories c WHERE c.name ilike 'Coffee';
INSERT INTO idea_categories (idea_id, category_id) SELECT 19,c.id FROM categories c WHERE c.name ilike 'Tea';
INSERT INTO idea_categories (idea_id, category_id) SELECT 19,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 20,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 20,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 21,c.id FROM categories c WHERE c.name ilike 'Coffee';
INSERT INTO idea_categories (idea_id, category_id) SELECT 21,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 21,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 22,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 22,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 23,c.id FROM categories c WHERE c.name ilike 'Smartwatches';
INSERT INTO idea_categories (idea_id, category_id) SELECT 24,c.id FROM categories c WHERE c.name ilike 'Photography';
INSERT INTO idea_categories (idea_id, category_id) SELECT 25,c.id FROM categories c WHERE c.name ilike 'Photography';
INSERT INTO idea_categories (idea_id, category_id) SELECT 26,c.id FROM categories c WHERE c.name ilike 'Photography';
INSERT INTO idea_categories (idea_id, category_id) SELECT 27,c.id FROM categories c WHERE c.name ilike 'Wireless Earbuds';
INSERT INTO idea_categories (idea_id, category_id) SELECT 28,c.id FROM categories c WHERE c.name ilike 'Wireless Earbuds';
INSERT INTO idea_categories (idea_id, category_id) SELECT 29,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 29,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 30,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 30,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 31,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 32,c.id FROM categories c WHERE c.name ilike 'VR Headsets';
INSERT INTO idea_categories (idea_id, category_id) SELECT 33,c.id FROM categories c WHERE c.name ilike 'Laptops';
INSERT INTO idea_categories (idea_id, category_id) SELECT 34,c.id FROM categories c WHERE c.name ilike 'Laptops';
INSERT INTO idea_categories (idea_id, category_id) SELECT 35,c.id FROM categories c WHERE c.name ilike 'Music';
INSERT INTO idea_categories (idea_id, category_id) SELECT 36,c.id FROM categories c WHERE c.name ilike 'Smartwatches';
INSERT INTO idea_categories (idea_id, category_id) SELECT 37,c.id FROM categories c WHERE c.name ilike 'Photography';
INSERT INTO idea_categories (idea_id, category_id) SELECT 38,c.id FROM categories c WHERE c.name ilike 'Board Games';
INSERT INTO idea_categories (idea_id, category_id) SELECT 38,c.id FROM categories c WHERE c.name ilike 'Toys';
INSERT INTO idea_categories (idea_id, category_id) SELECT 38,c.id FROM categories c WHERE c.name ilike 'DIY Crafts';
INSERT INTO idea_categories (idea_id, category_id) SELECT 39,c.id FROM categories c WHERE c.name ilike 'Board Games';
INSERT INTO idea_categories (idea_id, category_id) SELECT 39,c.id FROM categories c WHERE c.name ilike 'Toys';
INSERT INTO idea_categories (idea_id, category_id) SELECT 39,c.id FROM categories c WHERE c.name ilike 'DIY Crafts';
INSERT INTO idea_categories (idea_id, category_id) SELECT 40,c.id FROM categories c WHERE c.name ilike 'Board Games';
INSERT INTO idea_categories (idea_id, category_id) SELECT 40,c.id FROM categories c WHERE c.name ilike 'Toys';
INSERT INTO idea_categories (idea_id, category_id) SELECT 40,c.id FROM categories c WHERE c.name ilike 'DIY Crafts';
INSERT INTO idea_categories (idea_id, category_id) SELECT 41,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 41,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 42,c.id FROM categories c WHERE c.name ilike 'Coffee';
INSERT INTO idea_categories (idea_id, category_id) SELECT 42,c.id FROM categories c WHERE c.name ilike 'Kitchen supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 42,c.id FROM categories c WHERE c.name ilike 'Home essentials';
INSERT INTO idea_categories (idea_id, category_id) SELECT 43,c.id FROM categories c WHERE c.name ilike 'Sports';
INSERT INTO idea_categories (idea_id, category_id) SELECT 43,c.id FROM categories c WHERE c.name ilike 'Fishing';
INSERT INTO idea_categories (idea_id, category_id) SELECT 44,c.id FROM categories c WHERE c.name ilike 'Sports';
INSERT INTO idea_categories (idea_id, category_id) SELECT 44,c.id FROM categories c WHERE c.name ilike 'Fishing';
INSERT INTO idea_categories (idea_id, category_id) SELECT 45,c.id FROM categories c WHERE c.name ilike 'winter-wear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 45,c.id FROM categories c WHERE c.name ilike 'Hiking';
INSERT INTO idea_categories (idea_id, category_id) SELECT 45,c.id FROM categories c WHERE c.name ilike 'Skiing';
INSERT INTO idea_categories (idea_id, category_id) SELECT 46,c.id FROM categories c WHERE c.name ilike 'winter-wear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 46,c.id FROM categories c WHERE c.name ilike 'Hiking';
INSERT INTO idea_categories (idea_id, category_id) SELECT 46,c.id FROM categories c WHERE c.name ilike 'Skiing';
INSERT INTO idea_categories (idea_id, category_id) SELECT 47,c.id FROM categories c WHERE c.name ilike 'winter-wear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 47,c.id FROM categories c WHERE c.name ilike 'Hiking';
INSERT INTO idea_categories (idea_id, category_id) SELECT 48,c.id FROM categories c WHERE c.name ilike 'Hiking';
INSERT INTO idea_categories (idea_id, category_id) SELECT 48,c.id FROM categories c WHERE c.name ilike 'Camping';
INSERT INTO idea_categories (idea_id, category_id) SELECT 49,c.id FROM categories c WHERE c.name ilike 'Beach Trips';
INSERT INTO idea_categories (idea_id, category_id) SELECT 49,c.id FROM categories c WHERE c.name ilike 'Streetwear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 50,c.id FROM categories c WHERE c.name ilike 'Sunglasses';
INSERT INTO idea_categories (idea_id, category_id) SELECT 50,c.id FROM categories c WHERE c.name ilike 'Streetwear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 51,c.id FROM categories c WHERE c.name ilike 'Sunglasses';
INSERT INTO idea_categories (idea_id, category_id) SELECT 51,c.id FROM categories c WHERE c.name ilike 'Streetwear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 52,c.id FROM categories c WHERE c.name ilike 'Watches';
INSERT INTO idea_categories (idea_id, category_id) SELECT 53,c.id FROM categories c WHERE c.name ilike 'Handbags';
INSERT INTO idea_categories (idea_id, category_id) SELECT 54,c.id FROM categories c WHERE c.name ilike 'Handbags';
INSERT INTO idea_categories (idea_id, category_id) SELECT 55,c.id FROM categories c WHERE c.name ilike 'Jewelry';
INSERT INTO idea_categories (idea_id, category_id) SELECT 56,c.id FROM categories c WHERE c.name ilike 'Jewelry';
INSERT INTO idea_categories (idea_id, category_id) SELECT 57,c.id FROM categories c WHERE c.name ilike 'Vintage Clothing';
INSERT INTO idea_categories (idea_id, category_id) SELECT 58,c.id FROM categories c WHERE c.name ilike 'Vintage Clothing';
INSERT INTO idea_categories (idea_id, category_id) SELECT 58,c.id FROM categories c WHERE c.name ilike 'Streetwear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 59,c.id FROM categories c WHERE c.name ilike 'Sneakers';
INSERT INTO idea_categories (idea_id, category_id) SELECT 60,c.id FROM categories c WHERE c.name ilike 'Sneakers';
INSERT INTO idea_categories (idea_id, category_id) SELECT 61,c.id FROM categories c WHERE c.name ilike 'Sneakers';
INSERT INTO idea_categories (idea_id, category_id) SELECT 61,c.id FROM categories c WHERE c.name ilike 'Streetwear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 62,c.id FROM categories c WHERE c.name ilike 'Cozy Blankets';
INSERT INTO idea_categories (idea_id, category_id) SELECT 63,c.id FROM categories c WHERE c.name ilike 'Luxury Clothing';
INSERT INTO idea_categories (idea_id, category_id) SELECT 64,c.id FROM categories c WHERE c.name ilike 'Beanies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 64,c.id FROM categories c WHERE c.name ilike 'winter-wear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 64,c.id FROM categories c WHERE c.name ilike 'Hiking';
INSERT INTO idea_categories (idea_id, category_id) SELECT 65,c.id FROM categories c WHERE c.name ilike 'winter-wear';
INSERT INTO idea_categories (idea_id, category_id) SELECT 65,c.id FROM categories c WHERE c.name ilike 'Hiking';
INSERT INTO idea_categories (idea_id, category_id) SELECT 66,c.id FROM categories c WHERE c.name ilike 'Yoga';
INSERT INTO idea_categories (idea_id, category_id) SELECT 66,c.id FROM categories c WHERE c.name ilike 'Exercise';
INSERT INTO idea_categories (idea_id, category_id) SELECT 67,c.id FROM categories c WHERE c.name ilike 'Yoga';
INSERT INTO idea_categories (idea_id, category_id) SELECT 67,c.id FROM categories c WHERE c.name ilike 'Exercise';
INSERT INTO idea_categories (idea_id, category_id) SELECT 68,c.id FROM categories c WHERE c.name ilike 'Cycling';
INSERT INTO idea_categories (idea_id, category_id) SELECT 68,c.id FROM categories c WHERE c.name ilike 'Exercise';
INSERT INTO idea_categories (idea_id, category_id) SELECT 69,c.id FROM categories c WHERE c.name ilike 'Camping';
INSERT INTO idea_categories (idea_id, category_id) SELECT 70,c.id FROM categories c WHERE c.name ilike 'Camping';
INSERT INTO idea_categories (idea_id, category_id) SELECT 71,c.id FROM categories c WHERE c.name ilike 'Camping';
INSERT INTO idea_categories (idea_id, category_id) SELECT 72,c.id FROM categories c WHERE c.name ilike 'Camping';
INSERT INTO idea_categories (idea_id, category_id) SELECT 73,c.id FROM categories c WHERE c.name ilike 'Camping';
INSERT INTO idea_categories (idea_id, category_id) SELECT 74,c.id FROM categories c WHERE c.name ilike 'Office supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 75,c.id FROM categories c WHERE c.name ilike 'Office supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 76,c.id FROM categories c WHERE c.name ilike 'Smartphones';
INSERT INTO idea_categories (idea_id, category_id) SELECT 77,c.id FROM categories c WHERE c.name ilike 'Smartphones';
INSERT INTO idea_categories (idea_id, category_id) SELECT 78,c.id FROM categories c WHERE c.name ilike 'Smartphones';
INSERT INTO idea_categories (idea_id, category_id) SELECT 79,c.id FROM categories c WHERE c.name ilike 'Smartphones';
INSERT INTO idea_categories (idea_id, category_id) SELECT 80,c.id FROM categories c WHERE c.name ilike 'Video games';
INSERT INTO idea_categories (idea_id, category_id) SELECT 80,c.id FROM categories c WHERE c.name ilike 'Gaming Consoles';
INSERT INTO idea_categories (idea_id, category_id) SELECT 81,c.id FROM categories c WHERE c.name ilike 'Video games';
INSERT INTO idea_categories (idea_id, category_id) SELECT 81,c.id FROM categories c WHERE c.name ilike 'Gaming Consoles';
INSERT INTO idea_categories (idea_id, category_id) SELECT 82,c.id FROM categories c WHERE c.name ilike 'Video games';
INSERT INTO idea_categories (idea_id, category_id) SELECT 82,c.id FROM categories c WHERE c.name ilike 'Gaming Consoles';
INSERT INTO idea_categories (idea_id, category_id) SELECT 83,c.id FROM categories c WHERE c.name ilike 'Video games';
INSERT INTO idea_categories (idea_id, category_id) SELECT 83,c.id FROM categories c WHERE c.name ilike 'Gaming Consoles';
INSERT INTO idea_categories (idea_id, category_id) SELECT 84,c.id FROM categories c WHERE c.name ilike 'Office supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 84,c.id FROM categories c WHERE c.name ilike 'Photography';
INSERT INTO idea_categories (idea_id, category_id) SELECT 85,c.id FROM categories c WHERE c.name ilike 'Office supplies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 85,c.id FROM categories c WHERE c.name ilike 'Photography';
INSERT INTO idea_categories (idea_id, category_id) SELECT 86,c.id FROM categories c WHERE c.name ilike 'Mechanical Keyboards';
INSERT INTO idea_categories (idea_id, category_id) SELECT 87,c.id FROM categories c WHERE c.name ilike 'Music';
INSERT INTO idea_categories (idea_id, category_id) SELECT 88,c.id FROM categories c WHERE c.name ilike 'Beauty';
INSERT INTO idea_categories (idea_id, category_id) SELECT 89,c.id FROM categories c WHERE c.name ilike 'Comics';
INSERT INTO idea_categories (idea_id, category_id) SELECT 89,c.id FROM categories c WHERE c.name ilike 'Graphic Novels';
INSERT INTO idea_categories (idea_id, category_id) SELECT 90,c.id FROM categories c WHERE c.name ilike 'Toys';
INSERT INTO idea_categories (idea_id, category_id) SELECT 90,c.id FROM categories c WHERE c.name ilike 'Movies';
INSERT INTO idea_categories (idea_id, category_id) SELECT 91,c.id FROM categories c WHERE c.name ilike 'Video games';
INSERT INTO idea_categories (idea_id, category_id) SELECT 92,c.id FROM categories c WHERE c.name ilike 'Music';
INSERT INTO idea_categories (idea_id, category_id) SELECT 93,c.id FROM categories c WHERE c.name ilike 'Books';
INSERT INTO idea_categories (idea_id, category_id) SELECT 94,c.id FROM categories c WHERE c.name ilike 'Spicy Food';
INSERT INTO idea_categories (idea_id, category_id) SELECT 95,c.id FROM categories c WHERE c.name ilike 'Podcasts';
INSERT INTO idea_categories (idea_id, category_id) SELECT 96,c.id FROM categories c WHERE c.name ilike 'Camping';
INSERT INTO idea_categories (idea_id, category_id) SELECT 97,c.id FROM categories c WHERE c.name ilike 'Anime';
INSERT INTO idea_categories (idea_id, category_id) SELECT 97,c.id FROM categories c WHERE c.name ilike 'TV Shows';
INSERT INTO idea_categories (idea_id, category_id) SELECT 98,c.id FROM categories c WHERE c.name ilike 'Drawing';
INSERT INTO idea_categories (idea_id, category_id) SELECT 99,c.id FROM categories c WHERE c.name ilike 'Dogs';
INSERT INTO idea_categories (idea_id, category_id) SELECT 100,c.id FROM categories c WHERE c.name ilike 'Luxury Bedding';
